Stepper controller node
hugbed/strabus-ros pull request #3
Opened 2016-10-25 21:16 UTC by Buzzzsaw

Working stepper controller node in the Catkin workspace.
Still some testing to do with the SPI controller, and some improvements are still to be made to it.

2016-10-28 16:33 UTC, mgaudreault reviewed
Minor changes to do

2016-10-28 16:33 UTC, mgaudreault commented on stepper/README.md
> + * /stepper_controller_run : issue a command to an LED (on, off, blink)
Stepper LED ?

2016-10-28 16:33 UTC, mgaudreault commented on stepper/stepper_controller/src/loltest.py
> +#! /usr/bin/env python
Please change filename to something relevant or remove the file

2016-10-28 18:11 UTC, Buzzzsaw commented on stepper/README.md
> + * /stepper_controller_run : issue a command to an LED (on, off, blink)
Whoops! Copy paste error, good catch.

2016-10-28 18:11 UTC, Buzzzsaw commented on stepper/stepper_controller/src/loltest.py
> +#! /usr/bin/env python
Will be removed since not useful anymore.

2016-10-28 18:20 UTC, Buzzzsaw commented on stepper/README.md
> + * /stepper_controller_run : issue a command to an LED (on, off, blink)
Improved README au passage with the latest changes.

2016-11-02 19:04 UTC, carapas requested changes
Really great!
I would like to discuss about the JSON part of my review before pushing.

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +        StepTick2 = int(StepSec2 * self.STEP_ACC_RATIO)
int() is the equivalent for floor(). If precision is important here we should probably use math.round()

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +        StepTick = int(StepSec * self.STEP_SPEED_RATIO)
int() is the equivalent for floor(). If precision is important here we should probably use math.round()

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +        return StepTick2
return min(StepTick2, 0x00000FFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +        return StepTick
return min(StepTick, 0x000FFFFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +        return StepTick
return min(StepTick, 0x000FFFFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            Value = 0x00FFFFFF
Value = min(Value, 0x00FFFFFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            Steps = 0x003FFFFF
Steps = min(Steps, 0x003FFFFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            Position = 0x003FFFFF
Position = min(Position, 0x003FFFFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            Position = 0x003FFFFF
Position = min(Position, 0x003FFFFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            MinSpeed = 0x0FFF
MinSpeed = min(MinSpeed, 0x0FFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            MaxSpeed = 0x03FF
MaxSpeed = min(MaxSpeed, 0x03FF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            MinSpeed += 0x1000
Your way is probably cleaner, but here's a neat python golf trick:
`MinSpeed += (0, 0x1000)[Optimized]`

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            ThresholdSpeed = 0x03FF
ThresholdSpeed = min(ThresholdSpeed, 0x03FF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/include/L6470_pkg/L6470_lib.py
> +            Alarms = 0xFF
Alarms = min(Alarms, 0xFF)

2016-11-02 19:04 UTC, carapas commented on stepper/stepper_controller/src/stepper_controller_node.py
> +from stepper_controller.msg import Stop
Importing theses messages in node.js might be a pain. Maybe using std_msgs.String and using JSON would be a more standardised way of communicating?

2016-11-23 19:56 UTC, hugbed commented
Node should subscribe to topic : /motor/inter_eye/command

2016-11-23 21:51 UTC, mgaudreault commented
Fixed hugbed request, but we need more error handling I think, might do that tomorrow.

2016-11-28 17:00 UTC, merged